tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "caskroom/versions"

brew "zsh"
brew "zsh-completions"
brew "git"
brew "diff-so-fancy"
brew "tig"

brew "ripgrep"
brew "fd"
brew "tree"
brew "htop"
brew "tldr"
brew "jq"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["with-jansson", "HEAD"]

brew "vim"
brew "neovim"

brew "reattach-to-user-namespace"
brew "tmux"

brew "zsh"

cask "alfred"

cask "brave-browser"
cask "firefox-developer-edition"
cask "chrome"

cask "font-fira-code"
cask "hyper"
cask "iterm2"

cask "rectangle"
cask "spotify"
cask "flux"
cask "visual-studio-code"
