tap "homebrew/core"
tap "homebrew/bundle"

tap "homebrew/cask"
tap "caskroom/cask-versions"

tap "homebrew/cask-fonts"

brew "zsh"
brew "git"
brew "diff-so-fancy"
brew "tig"

brew "ripgrep"
brew "fd"
brew "tree"
brew "htop"
brew "tldr"
brew "jq"
brew "rename"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

brew "neovim"

brew "reattach-to-user-namespace"
brew "tmux"

cask "alfred"

cask "brave-browser"
cask "firefox-developer-edition"

cask "font-jetbrainsmono-nerd-font"

cask "kitty"
cask "flux"
cask "visual-studio-code"
cask "rectangle"
