tap "homebrew/core"
tap "homebrew/bundle"

tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

# git
brew "git"
brew "diff-so-fancy"
brew "tig"
brew "lazygit"

# vim
brew "neovim", args: ["HEAD"]
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

# shell
brew "zsh"
brew "ripgrep"
brew "fd"
brew "bat"
brew "tree"
brew "htop"
brew "jq"
brew "curl"
brew "wget"

# term
brew "tmux"
brew "reattach-to-user-namespace"
cask "kitty"

# apps
cask "alfred"
cask "visual-studio-code"
cask "rectangle"
cask "bitwarden"
cask "brave-browser"
cask "discord"
cask "whatsapp"

# fonts
cask "font-jetbrains-mono-nerd-font"

