tap "homebrew/core"
tap "homebrew/bundle"

tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

# nvim
brew "neovim", args: ["HEAD"]
brew "universal-ctags"

# shell
brew "zsh"
brew "tmux"
brew "reattach-to-user-namespace"
## git
brew "git"
brew "lazygit"
## utils
brew "ripgrep"
brew "fd"
brew "bat"
brew "tree"
brew "htop"
brew "jq"
brew "curl"
brew "wget"

# terminal
cask "kitty"
cask "warp"
cask "hyper"
cask "alacritty"
cask "fig"

# apps
cask "alfred"
cask "raycast"
cask "penc"
cask "visual-studio-code"
cask "bitwarden"
cask "brave-browser"
cask "discord"
cask "whatsapp"

# fonts
cask "font-jetbrains-mono-nerd-font"
