#####################################
# Oh-My-Zsh Setup

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="refined"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy/mm/dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  vi-mode
  fasd
  zsh-nvm
  zsh-better-npm-completion
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
)

# reset prompt
DEFAULT_USER=$USER
prompt_context() {}

# zsh-nvm config must be run before sourcing oh-my-zsh
# if set to true nvm will not auto load on start up
NVM_LAZY_LOAD=true
# if set to true nvm use <version> must be used explicitly before running node/npm commands
NVM_NO_USE=false
# call nvm use automatically when you cd into a dir with .nvmrc
NVM_AUTO_USE=false

source $ZSH/oh-my-zsh.sh


#####################################
# Plugins
#

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan' # set completion color to cyan
bindkey '^ ' autosuggest-accept           # ctrl+space to accept suggestion

# z
export _Z_DATA=~/.z.datafile
. ~/.z/z.sh

# fzf
if [ -f ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
else
  ~/.fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish
fi


#####################################
# Functions
#

# nvm slows up zsh ALOT if nvm is needed run nvm_start command
function nvm_start() {
  export NVM_DIR="$(realpath ~/.nvm)"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
}

# do a fuzzy checkout in the shell using git.
# pass update as second param to git fetch and pull all the things before and after checkout
function fcheckout() {
  if [ "$1" = "update" ]; then
    git fetch
  fi
  local branches branch
  branches=$(git branch -a) &&
    branch=$(echo "$branches" | fzf +s +m -e) &&
    git checkout $(echo "$branch" | sed "s:.* remotes/origin/::" | sed "s:.* ::")
  if [ "$1" = "update" ]; then
    git pull
  fi
}


#####################################
# Alias
#

# git
alias g='git'
alias gs='git status'
alias gsr='git submodule foreach --recursive git reset --hard'
alias gsu='git submodule update --init --recursive --remote'
alias gprune='git remote prune origin && git branch --merged | grep -Ev \"(\\*|master)\" | xargs git branch -d"'
alias l='ls -all'
alias fv='f -e vim'

# use nvim if possible, vim otherwise
if [ -x "$(command -v nvim)" ]; then
  alias vim=nvim
fi

# use vscode-insiders as default code exec if exists
if [ -x "$(command -v code-insiders)" ]; then
  alias code=code-insiders
fi

# run this command in the root of the dotfiles repo
alias dotfiles_update='gsr && gsu && gsr; ./install'

# git
git config --global alias.lg !"git log --stat --diff-algorithm=minimal --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'"


#####################################
# Misc
#

# lang
export LANG=en_US.UTF-8

# Brew shell completion for zsh. For more information visit: https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# git
git config --global mergetool.keepBackup false


#####################################
