#####################################
# Alias
# Common shared alias between shells

# git
alias g='git'
alias gs='git status'
alias gsr='git submodule foreach --recursive git reset --hard'
alias gsu='git submodule update --init --recursive --remote'
alias gprune='git remote prune origin && git branch --merged | grep -Ev \"(\\*|master)\" | xargs git branch -d"'

# misc
alias l='ls -all'

# use nvim if possible, vim otherwise
if [ -x "$(command -v nvim)" ]; then
  alias vim=nvim
fi

# use vscode-insiders as default code exec if exists
if [ -x "$(command -v code-insiders)" ]; then
  alias code=code-insiders
fi

# run this command in the root of the dotfiles repo to update it
alias dotfiles_update='gsr && gsu && gsr; ./install'
